language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
before_install:
  - "mkdir -p ~/.npm"
install:
  - npm install
  - npm install git://github.com/hybridgroup/cylon.git
  - npm install -g istanbul codeclimate-test-reporter
script:
  - make ci
  - CODECLIMATE_REPO_TOKEN=46646e4c497d23fcacca3cdfc812cf5f44722dce66aea4742419d53c8254d81c codeclimate-test-reporter < coverage/lcov.info
